name: yourkids
favicon: null
layout_spectrum: 0.10240038321353495
typography_spectrum: 0.10844762506894767
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c71c22'
    - '#fef200'
    - '#ffffff'
    - '#f9a61a'
    - '#341718'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
