layout_spectrum: 0.06639633329511427
typography_spectrum: 0.9005936549197292
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.16916693417936343
  lightness: 0.2587736377718462
  saturation: 0.8828843996276396
  rhythmicContrast: 0.7549943874110606
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/55429f3f-9478-423e-8b92-f4a1cbd9562d.png
name: Yourkids
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/32e95533-687c-4d72-9cec-da27b9f135f9.png
title: Your Kids & the Internet
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FwWW_UbrkBEw%3Fstart%3D9%26feature%3Doembed%26start%3D9&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DwWW_UbrkBEw&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FwWW_UbrkBEw%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: KQED Art School
          url: 'https://www.youtube.com/channel/UCo-WcbYJeYrORqnVTzBoApA'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: youtu.be
      keywords:
        - color (quotation subject)
        - kqed-fm (award winner)
        - the arts (broadcast genre)
        - elements of art
        - kqed (broadcast)
        - public broadcasting service (tv network)
        - p...
      description: >-
        Brush up on your knowledge of color in the sixth installment of our
        Elements of Art series. By considering the vital and vibrant work of the
        Color Field painters of the 1950s and 60s, we get a glimpse of how
        powerful a role color plays in art.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=wWW_UbrkBEw&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=wWW_UbrkBEw&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=wWW_UbrkBEw&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=wWW_UbrkBEw&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=wWW_UbrkBEw&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=wWW_UbrkBEw'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=wWW_UbrkBEw
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=wWW_UbrkBEw
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/wWW_UbrkBEw?t=9'
      title: 'Elements of Art: Color | KQED Arts'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  The latest news & views about your kids online. What's good, what's bad, and
  what you can do about it
purpose:
  - type: internal
    label: Good for Kids Online
    item: 26cf966c-debd-4d28-9d84-696986f133de
  - type: internal
    label: Bad for Kids Online
    item: 8ffc4a6f-8406-4057-a2a7-39ab6a3d5006
content_rating:
  adult: false
author:
  name: Mark Trudinger
  email: mark@yourkids.com
url: 'https://yourkids.com/'
github: true
