layout_spectrum: 0.06639633329511427
typography_spectrum: 0.9005936549197292
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.16916693417936343
  lightness: 0.2587736377718462
  saturation: 0.8828843996276396
  rhythmicContrast: 0.7549943874110606
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/55429f3f-9478-423e-8b92-f4a1cbd9562d.png
name: Yourkids
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/32e95533-687c-4d72-9cec-da27b9f135f9.png
title: Your Kids & the Internet
content: []
description: >-
  The latest news & views about your kids online. What's good, what's bad, and
  what you can do about it
purpose:
  - type: internal
    label: Good for Kids Online
    item: 26cf966c-debd-4d28-9d84-696986f133de
  - type: internal
    label: Bad for Kids Online
    item: 8ffc4a6f-8406-4057-a2a7-39ab6a3d5006
content_rating:
  adult: false
author:
  name: Mark Trudinger
  email: mark@yourkids.com
url: 'https://yourkids.com/'
github: true
